spring:
  application:
    name: payment-service

  main:
    allow-bean-definition-overriding: true

  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:10002}"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:10001/eureka/}